# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 29, 15, 17, 2, 456481)),
        ),
    ]
