# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionManagement', '0002_breakfast_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('protien', models.FloatField(blank=True)),
                ('carbohydrates', models.FloatField(blank=True)),
                ('fat', models.FloatField(blank=True)),
                ('vitamin', models.FloatField(blank=True)),
                ('mineral', models.FloatField(blank=True)),
                ('calorie', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 29, 23, 11, 40, 2639)),
        ),
    ]
