# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionManagement', '0003_auto_20170929_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 9, 29, 23, 15, 9, 223274)),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='mineral',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='protien',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='vitamin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
