# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NutritionManagement', '0007_auto_20170930_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 6, 23, 6, 46, 489968)),
        ),
    ]
